/*
 * CleanRam
 * Version 1.0
 * Copyright (C) GiusNiyyel, Inc - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Daniel Campos <giusniyyel@gmail.com>, January 2019
 */
package com.giusniyyel.cleanram.v1;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author GiusNiyyel
 */
public class CleanRam_es_TM extends javax.swing.JFrame {

    /**
     * Creates new form CleanRam_es_TM
     */
    public CleanRam_es_TM() {
        initComponents();
        setTitle("Selección de Ram - CleanRam v1.0 by GiusNiyyel");
        setIconImage(new ImageIcon(getClass().getResource("/com/giusniyyel/cleanram/v1/src/cleanram-icon.png")).getImage());
        setResizable(false);
        this.setSize(515,184);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbMT = new javax.swing.JComboBox<>();
        btnMT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        cmbMT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 GB", "2 GB", "4 GB", "6 GB", "8 GB", "12 GB", "16 GB", "32 GB", "64 GB", "128 GB" }));
        cmbMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMTActionPerformed(evt);
            }
        });
        getContentPane().add(cmbMT);
        cmbMT.setBounds(214, 80, 65, 20);

        btnMT.setText("Aplicar");
        btnMT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMTActionPerformed(evt);
            }
        });
        getContentPane().add(btnMT);
        btnMT.setBounds(214, 118, 65, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/giusniyyel/cleanram/v1/src/BG2.png"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 515, 184);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMTActionPerformed
        Archivo a = new Archivo();
        int i=cmbMT.getSelectedIndex();
        String p;
        String appDataDirectory;
        /*Concatena el directorio de APPDATA y el archivo*/
        appDataDirectory = System.getenv("APPDATA");
        p = "\\giusniyyel\\cleanram\\ramsize.txt";
        String arcf = appDataDirectory + p;
        try{
            if(i==0){
                a.Escribir(arcf, "1");
            }
            if(i==1){
                a.Escribir(arcf, "2");
            }
            if(i==2){
                a.Escribir(arcf, "4");
            }
            if(i==3){
                a.Escribir(arcf, "6");
            }
            if(i==4){
                a.Escribir(arcf, "8");
            }
            if(i==5){
                a.Escribir(arcf, "12");
            }
            if(i==6){
                a.Escribir(arcf, "16");
            }
            if(i==7){
                a.Escribir(arcf, "32");
            }
            if(i==8){
                a.Escribir(arcf, "64");
            }
            if(i==9){
                a.Escribir(arcf, "128");
            }
            JOptionPane.showMessageDialog(null, "Se ha configurado el tamaño de RAM correctamente","CleanRam",JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "No se ha podido configurar el tamaño de RAM, Error: "+e,"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnMTActionPerformed

    private void cmbMTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMTActionPerformed
        
    }//GEN-LAST:event_cmbMTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CleanRam_es_TM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CleanRam_es_TM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CleanRam_es_TM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CleanRam_es_TM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CleanRam_es_TM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMT;
    private javax.swing.JComboBox<String> cmbMT;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
