/*
 * CleanRam
 * Version 1.0
 * Copyright (C) GiusNiyyel, Inc - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Daniel Campos <giusniyyel@gmail.com>, January 2019
 */
package com.giusniyyel.cleanram.v1;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author GiusNiyyel
 */
public class CleanRam_es extends javax.swing.JFrame {

    /**
     * Creates new form CleanRam
     */
    public CleanRam_es() {
        initComponents();
        /* NOMBRE QUE MUESTRA */
        setTitle("CleanRam v1.0 by GiusNiyyel");
        /* ICONO DEL SOFTWARE */
        setIconImage(new ImageIcon(getClass().getResource("/com/giusniyyel/cleanram/v1/src/cleanram-icon.png")).getImage());
        /* REGLAS OTORGADAS AL JFRAME */
        setResizable(false);
        /* Fondo */
        this.setSize(1024,600);
        /*Ocultar*/
        lblBar.setVisible(false);
        this.setLocationRelativeTo(null);
    }
    
    public void borrarDirectorio(File directory){
        File[] ficheros = directory.listFiles();
        for(int x=0;x<ficheros.length;x++){
            if (ficheros[x].isDirectory()){
                borrarDirectorio (ficheros [x]);
            }
            ficheros[x].delete();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTM = new javax.swing.JButton();
        btnLR = new javax.swing.JButton();
        btnLC = new javax.swing.JButton();
        lblCopy = new javax.swing.JLabel();
        lblBar = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1024, 600));
        setSize(new java.awt.Dimension(1024, 600));

        btnTM.setBackground(new java.awt.Color(204, 255, 204));
        btnTM.setForeground(new java.awt.Color(51, 255, 51));
        btnTM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/giusniyyel/cleanram/v1/src/TM.png"))); // NOI18N
        btnTM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTMActionPerformed(evt);
            }
        });

        btnLR.setBackground(new java.awt.Color(204, 255, 204));
        btnLR.setForeground(new java.awt.Color(51, 255, 51));
        btnLR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/giusniyyel/cleanram/v1/src/LR.png"))); // NOI18N
        btnLR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLRActionPerformed(evt);
            }
        });

        btnLC.setBackground(new java.awt.Color(204, 255, 204));
        btnLC.setForeground(new java.awt.Color(51, 255, 51));
        btnLC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/giusniyyel/cleanram/v1/src/LC.png"))); // NOI18N
        btnLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLCActionPerformed(evt);
            }
        });

        lblCopy.setForeground(new java.awt.Color(125, 231, 87));
        lblCopy.setText("by GiusNiyyel");

        lblBar.setForeground(new java.awt.Color(125, 231, 87));
        lblBar.setText("Eliminando...");
        lblBar.setToolTipText("");

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/giusniyyel/cleanram/v1/src/BG.png"))); // NOI18N
        bg.setText("jLabel1");
        bg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnTM, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnLR, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(480, 480, 480)
                .addComponent(lblBar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(710, 710, 710)
                .addComponent(btnLC, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(940, 940, 940)
                .addComponent(lblCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTM, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLR, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(lblBar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(btnLC, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(550, 550, 550)
                .addComponent(lblCopy))
            .addComponent(bg)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTMActionPerformed
        CleanRam_es_TM tm = new CleanRam_es_TM();
        tm.setVisible(true);
    }//GEN-LAST:event_btnTMActionPerformed

    private void btnLRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLRActionPerformed
        String p;
        String appDataDirectory;
        /*Concatena el directorio de APPDATA y el archivo*/
        appDataDirectory = System.getenv("APPDATA");
        p = "\\giusniyyel\\cleanram\\ramsize.txt";
        String arcf = appDataDirectory + p;
        File f = new File(arcf);       
        if(f.exists()){
            Archivo a = new Archivo();
            try{
                a.Leer(arcf);
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, "No se ha podido ejecutar esta acción, Error: "+e,"Error",JOptionPane.ERROR_MESSAGE);
            }   
        }else{
            JOptionPane.showMessageDialog(null, "¡Oye, no has seleccionado el tamaño de tu RAM!","CleanRam",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLRActionPerformed

    private void btnLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLCActionPerformed
        String tempDirectory = System.getProperty("java.io.tmpdir");
        File f = new File(tempDirectory);
        lblBar.setVisible(true);
        borrarDirectorio(f);
        JOptionPane.showMessageDialog(null, "Se ha borrado los archivos temporales con exito","CleanRam",JOptionPane.INFORMATION_MESSAGE);
        lblBar.setVisible(false);
    }//GEN-LAST:event_btnLCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CleanRam_es.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CleanRam_es.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CleanRam_es.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CleanRam_es.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CleanRam_es().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnLC;
    private javax.swing.JButton btnLR;
    private javax.swing.JButton btnTM;
    private javax.swing.JLabel lblBar;
    private javax.swing.JLabel lblCopy;
    // End of variables declaration//GEN-END:variables
}
